### ISSUE TITLE
生成脚本，但是没有备份

### ISSUE THREAD

**Issue by jx3775250** [jeessy2/backup-db#1]
![image](https://user-images.githubusercontent.com/40455946/79634163-6c977280-819b-11ea-9e3d-18377add36ac.png)
手动运行脚本可以，但是不自动备份

**Comment by jeessy2** [comment]
看下docker的日志呢，docker logs xxx

**Comment by jx3775250** [comment]
![image](https://user-images.githubusercontent.com/40455946/79821131-89f95600-83c0-11ea-9962-7bc68ad0fd59.png)
![image](https://user-images.githubusercontent.com/40455946/79821278-ec525680-83c0-11ea-8721-6e3576eabb7f.png)

mysqldump命令我手动执行可以，但是机器执行就不行

**Comment by jeessy2** [comment]
![image](https://user-images.githubusercontent.com/6205259/79827409-c9c83980-83d0-11ea-99b9-d16d46c14164.png)
已经写的很清楚了。容器中没有mysqldump命令（即使你主机有也不行）。那就得看你创建容器的时候的命令是那个。
mysql5的命令下面这个。检查下是不是使用错了
```
docker run -d \
--name backup-db-name \
--restart=always \
-v /opt/backup-files:/app/backup-files \
-e backup_server_ip=192.168.1.76 \
-e backup_server_port=9977 \
-e server_secret_key=please_change_it \
-e backup_project_name=db-name \
-e backup_command="mysqldump -h192.168.1.9 -uroot -p123456 db-name > #{DATE}.sql" \
-e max_save_days=30 \
-e notice_email=xxx@qq.com \
-e smtp_host=smtp.office365.com \
-e smtp_port=587 \
-e smtp_username=backup-db-docker@outlook.com \
-e smtp_password=password \
jeessy/backup-db:mysql5-0.0.7
```

**Comment by jx3775250** [comment]
我是用的容器中的mysqldump命令可以备份，但是你这个脚本就不行，有没有可能是你程序没有加载到mysqldump的环境变量，改成shell脚本也是可以执行的！
![image](https://user-images.githubusercontent.com/40455946/79828747-f3369480-83d3-11ea-9af1-8a7f72f14d24.png)

**Comment by jx3775250** [comment]
我试下命令不带双引号看看有没有问题，我把脚本里面的双引号去掉手动执行时可以的
![image](https://user-images.githubusercontent.com/40455946/79829409-963bde00-83d5-11ea-8a3f-d97ef2e2eafe.png)

**Comment by jeessy2** [comment]
应该和引号没有关系，把引号去了有可能容器都起不来。你看下你那个容器使用的镜像版本是多少呢？
如果是shell脚本的话，putty会显示绿色。我看你的没有显示颜色
docker ps

**Comment by jeessy2** [comment]
还有个问题是容器里不知道iot-mysql的真实ip. 就连不上

**Comment by jx3775250** [comment]
已经解决了，我把引号去掉了就可以了，容器里面不是必须要真是IP的，可以通过容器名和容器ID来连接，不知道你生成的脚本里面有没有引号？
![image](https://user-images.githubusercontent.com/40455946/79830283-ae146180-83d7-11ea-99b9-22841a99d137.png)

**Comment by jx3775250** [comment]
![image](https://user-images.githubusercontent.com/40455946/79830330-c2f0f500-83d7-11ea-8659-cb07def3db28.png)

**Comment by jx3775250** [comment]
![image](https://user-images.githubusercontent.com/40455946/79830403-e156f080-83d7-11ea-8e93-f3d8b7222378.png)

**Comment by jeessy2** [comment]
生成的.sh文件里面是没有引号的，你也看到了，引号会被docker过滤传给程序。
你可以查看一下 docker inspect c58e46479c12 | grep backup_command

**Comment by jx3775250** [comment]
那应该是我这边没有过滤掉，我把双引号去掉了就可以了

**Comment by jeessy2** [comment]
好嘛，有问题在沟通。mysql是不需要引号的，postgres需要引号。我先把说明文档改了
